[package]
name = "hearth"
version = "0.2.0"
edition = "2024"
rust-version = "1.90.0"

[dependencies]
reqwest = { version = "0.13", features = ["stream", "json"] }
tokio = { version = "1", features = ["full"] }
tokio-retry = "0.3.0"
tokio-stream = { version = "0.1.17", features = ["fs"] }
futures = "0.3" # Needed by reqwest's stream feature
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
metrics = "0.24"
metrics-exporter-prometheus = { version = "0.18", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
config = "0.15"
thiserror = "2.0"
async-trait = "0.1"
strum = { version = "0.28", features = ["derive"] }
cron = "0.17"
chrono = { version = "0.4", features = ["serde"] }
ordered-float = "5.1.0"
humantime-serde = "1.1.1"
sunrise = "3.0"

# Webserver
axum = "0.8"

# Action macros
action_macros = { path = "action_macros" }
ctor = "1.0"

[dev-dependencies]
cargo-llvm-cov = "0.9"
mockito = "1.7"
pretty_assertions = "1.4"
rstest = "0.27"
test-log = { version = "0.2", features = ["trace"] }
